//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 09:59:14 AM COT 
//


package pruebas.registry;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://nequi.co/message/registry/ServiceRegistry/lookup}lookupResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyResponseType", propOrder = {
    "lookupResponse"
})
public class BodyResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://nequi.co/message/registry/ServiceRegistry/lookup")
    protected LookupResponseType lookupResponse;

    /**
     * Gets the value of the lookupResponse property.
     * 
     * @return
     *     possible object is
     *     {@link LookupResponseType }
     *     
     */
    public LookupResponseType getLookupResponse() {
        return lookupResponse;
    }

    /**
     * Sets the value of the lookupResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupResponseType }
     *     
     */
    public void setLookupResponse(LookupResponseType value) {
        this.lookupResponse = value;
    }

}
