//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 09:59:14 AM COT 
//


package pruebas.registry;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nequi.mbs.fis609.messaging.services.registry package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegistryRequest_QNAME = new QName("http://nequi.co/message/registry/ServiceRegistry", "registryRequest");
    private final static QName _LookupResponse_QNAME = new QName("http://nequi.co/message/registry/ServiceRegistry/lookup", "lookupResponse");
    private final static QName _RegistryResponse_QNAME = new QName("http://nequi.co/message/registry/ServiceRegistry", "registryResponse");
    private final static QName _LookupRequest_QNAME = new QName("http://nequi.co/message/registry/ServiceRegistry/lookup", "lookupRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nequi.mbs.fis609.messaging.services.registry
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistryResponseType }
     * 
     */
    public RegistryResponseType createRegistryResponseType() {
        return new RegistryResponseType();
    }

    /**
     * Create an instance of {@link RegistryRQ }
     * 
     */
    public RegistryRQ createRegistryRQ() {
        return new RegistryRQ();
    }

    /**
     * Create an instance of {@link RegistryRequestType }
     * 
     */
    public RegistryRequestType createRegistryRequestType() {
        return new RegistryRequestType();
    }

    /**
     * Create an instance of {@link RegistryRS }
     * 
     */
    public RegistryRS createRegistryRS() {
        return new RegistryRS();
    }

    /**
     * Create an instance of {@link ConsumerType }
     * 
     */
    public ConsumerType createConsumerType() {
        return new ConsumerType();
    }

    /**
     * Create an instance of {@link BodyRequestType }
     * 
     */
    public BodyRequestType createBodyRequestType() {
        return new BodyRequestType();
    }

    /**
     * Create an instance of {@link BodyResponseType }
     * 
     */
    public BodyResponseType createBodyResponseType() {
        return new BodyResponseType();
    }

    /**
     * Create an instance of {@link HeaderRequestType }
     * 
     */
    public HeaderRequestType createHeaderRequestType() {
        return new HeaderRequestType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link HeaderResponseType }
     * 
     */
    public HeaderResponseType createHeaderResponseType() {
        return new HeaderResponseType();
    }

    /**
     * Create an instance of {@link LookupResponseType }
     * 
     */
    public LookupResponseType createLookupResponseType() {
        return new LookupResponseType();
    }

    /**
     * Create an instance of {@link LookupRequestType }
     * 
     */
    public LookupRequestType createLookupRequestType() {
        return new LookupRequestType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link TimeoutType }
     * 
     */
    public TimeoutType createTimeoutType() {
        return new TimeoutType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/registry/ServiceRegistry", name = "registryRequest")
    public JAXBElement<RegistryRequestType> createRegistryRequest(RegistryRequestType value) {
        return new JAXBElement<RegistryRequestType>(_RegistryRequest_QNAME, RegistryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LookupResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/registry/ServiceRegistry/lookup", name = "lookupResponse")
    public JAXBElement<LookupResponseType> createLookupResponse(LookupResponseType value) {
        return new JAXBElement<LookupResponseType>(_LookupResponse_QNAME, LookupResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/registry/ServiceRegistry", name = "registryResponse")
    public JAXBElement<RegistryResponseType> createRegistryResponse(RegistryResponseType value) {
        return new JAXBElement<RegistryResponseType>(_RegistryResponse_QNAME, RegistryResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LookupRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/registry/ServiceRegistry/lookup", name = "lookupRequest")
    public JAXBElement<LookupRequestType> createLookupRequest(LookupRequestType value) {
        return new JAXBElement<LookupRequestType>(_LookupRequest_QNAME, LookupRequestType.class, null, value);
    }

}
