//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 09:59:14 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/message/registry/ServiceRegistry", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pruebas.registry;
