//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.03 at 06:20:06 PM COT 
//


package pruebas.bco.promotions;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://nequi.co/message/backout/services/promotions/bonus}backoutResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "backoutResponse"
})
@XmlRootElement(name = "backoutRS", namespace = "http://nequi.co/message/backout/services/promotions/bonus")
public class BackoutRS
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BackoutResponseType backoutResponse;

    /**
     * Gets the value of the backoutResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BackoutResponseType }
     *     
     */
    public BackoutResponseType getBackoutResponse() {
        return backoutResponse;
    }

    /**
     * Sets the value of the backoutResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackoutResponseType }
     *     
     */
    public void setBackoutResponse(BackoutResponseType value) {
        this.backoutResponse = value;
    }

}
