//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.03 at 06:20:06 PM COT 
//


package pruebas.bco.promotions;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bcoBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bcoBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="promoData" type="{http://nequi.co/message/backout/services/promotions/bonus}PromoDataType"/>
 *         &lt;element name="customerData" type="{http://nequi.co/message/backout/services/promotions/bonus}CustomerDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bcoBodyType", propOrder = {
    "promoData",
    "customerData"
})
public class BcoBodyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected PromoDataType promoData;
    @XmlElement(required = true)
    protected CustomerDataType customerData;

    /**
     * Gets the value of the promoData property.
     * 
     * @return
     *     possible object is
     *     {@link PromoDataType }
     *     
     */
    public PromoDataType getPromoData() {
        return promoData;
    }

    /**
     * Sets the value of the promoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromoDataType }
     *     
     */
    public void setPromoData(PromoDataType value) {
        this.promoData = value;
    }

    /**
     * Gets the value of the customerData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDataType }
     *     
     */
    public CustomerDataType getCustomerData() {
        return customerData;
    }

    /**
     * Sets the value of the customerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDataType }
     *     
     */
    public void setCustomerData(CustomerDataType value) {
        this.customerData = value;
    }

}
