//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.03 at 06:20:06 PM COT 
//


package pruebas.bco.promotions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pruebas.bco.promotions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BackoutResponse_QNAME = new QName("http://nequi.co/message/backout/services/promotions/bonus", "backoutResponse");
    private final static QName _BackoutRequest_QNAME = new QName("http://nequi.co/message/backout/services/promotions/bonus", "backoutRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pruebas.bco.promotions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BackoutRequestType }
     * 
     */
    public BackoutRequestType createBackoutRequestType() {
        return new BackoutRequestType();
    }

    /**
     * Create an instance of {@link BackoutRS }
     * 
     */
    public BackoutRS createBackoutRS() {
        return new BackoutRS();
    }

    /**
     * Create an instance of {@link BackoutResponseType }
     * 
     */
    public BackoutResponseType createBackoutResponseType() {
        return new BackoutResponseType();
    }

    /**
     * Create an instance of {@link BackoutRQ }
     * 
     */
    public BackoutRQ createBackoutRQ() {
        return new BackoutRQ();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link ConsumerType }
     * 
     */
    public ConsumerType createConsumerType() {
        return new ConsumerType();
    }

    /**
     * Create an instance of {@link PayloadType }
     * 
     */
    public PayloadType createPayloadType() {
        return new PayloadType();
    }

    /**
     * Create an instance of {@link BcoHeaderType }
     * 
     */
    public BcoHeaderType createBcoHeaderType() {
        return new BcoHeaderType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link PromoDataType }
     * 
     */
    public PromoDataType createPromoDataType() {
        return new PromoDataType();
    }

    /**
     * Create an instance of {@link ResponseBodyType }
     * 
     */
    public ResponseBodyType createResponseBodyType() {
        return new ResponseBodyType();
    }

    /**
     * Create an instance of {@link CustomerDataType }
     * 
     */
    public CustomerDataType createCustomerDataType() {
        return new CustomerDataType();
    }

    /**
     * Create an instance of {@link ResponseHeaderType }
     * 
     */
    public ResponseHeaderType createResponseHeaderType() {
        return new ResponseHeaderType();
    }

    /**
     * Create an instance of {@link CashBackDataType }
     * 
     */
    public CashBackDataType createCashBackDataType() {
        return new CashBackDataType();
    }

    /**
     * Create an instance of {@link BcoBodyType }
     * 
     */
    public BcoBodyType createBcoBodyType() {
        return new BcoBodyType();
    }

    /**
     * Create an instance of {@link CommerceType }
     * 
     */
    public CommerceType createCommerceType() {
        return new CommerceType();
    }

    /**
     * Create an instance of {@link BonusDataType }
     * 
     */
    public BonusDataType createBonusDataType() {
        return new BonusDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackoutResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/backout/services/promotions/bonus", name = "backoutResponse")
    public JAXBElement<BackoutResponseType> createBackoutResponse(BackoutResponseType value) {
        return new JAXBElement<BackoutResponseType>(_BackoutResponse_QNAME, BackoutResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackoutRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/backout/services/promotions/bonus", name = "backoutRequest")
    public JAXBElement<BackoutRequestType> createBackoutRequest(BackoutRequestType value) {
        return new JAXBElement<BackoutRequestType>(_BackoutRequest_QNAME, BackoutRequestType.class, null, value);
    }

}
