//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.03 at 05:22:26 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/message/bussines/services/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pruebas.seiya;
