//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 10:12:37 AM COT 
//


package pruebas.security;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="clearMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="protectMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "clearMessage",
    "protectMessage"
})
public class BodyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String clearMessage;
    protected String protectMessage;

    /**
     * Gets the value of the clearMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearMessage() {
        return clearMessage;
    }

    /**
     * Sets the value of the clearMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearMessage(String value) {
        this.clearMessage = value;
    }

    /**
     * Gets the value of the protectMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtectMessage() {
        return protectMessage;
    }

    /**
     * Sets the value of the protectMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtectMessage(String value) {
        this.protectMessage = value;
    }

}
