//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 10:12:37 AM COT 
//


package pruebas.security;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nequi.mbs.fis609.messaging.services.security package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SecurityResponse_QNAME = new QName("http://nequi.co/services/util/SecurityManager", "securityResponse");
    private final static QName _SecurityRequest_QNAME = new QName("http://nequi.co/services/util/SecurityManager", "securityRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nequi.mbs.fis609.messaging.services.security
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityRS }
     * 
     */
    public SecurityRS createSecurityRS() {
        return new SecurityRS();
    }

    /**
     * Create an instance of {@link SecurityResponseType }
     * 
     */
    public SecurityResponseType createSecurityResponseType() {
        return new SecurityResponseType();
    }

    /**
     * Create an instance of {@link SecurityRQ }
     * 
     */
    public SecurityRQ createSecurityRQ() {
        return new SecurityRQ();
    }

    /**
     * Create an instance of {@link SecurityRequestType }
     * 
     */
    public SecurityRequestType createSecurityRequestType() {
        return new SecurityRequestType();
    }

    /**
     * Create an instance of {@link BodyType }
     * 
     */
    public BodyType createBodyType() {
        return new BodyType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/services/util/SecurityManager", name = "securityResponse")
    public JAXBElement<SecurityResponseType> createSecurityResponse(SecurityResponseType value) {
        return new JAXBElement<SecurityResponseType>(_SecurityResponse_QNAME, SecurityResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/services/util/SecurityManager", name = "securityRequest")
    public JAXBElement<SecurityRequestType> createSecurityRequest(SecurityRequestType value) {
        return new JAXBElement<SecurityRequestType>(_SecurityRequest_QNAME, SecurityRequestType.class, null, value);
    }

}
