//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 10:12:37 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/services/util/SecurityManager", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pruebas.security;
